# Generated by Django 5.2.8 on 2025-12-04 05:24

import fileshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=fileshare.models.file_upload_path),
        ),
    ]
